"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.default = {
    "de": {
        credits: {
            "default": "Erstellt mit Flourish",
        },
    },
    "en": {
        credits: {
            "default": { text: "Made with Flourish • Create your own", url: "https://flourish.studio/" },
            "3d-arc-map": { text: "Made with Flourish • Create an arc map", url: "https://flourish.studio/visualisations/maps/" },
            "3d-map": { text: "Made with Flourish • Create a 3D map", url: "https://flourish.studio/visualisations/maps/" },
            "3d-marker-map": { text: "Made with Flourish • Create a marker map", url: "https://flourish.studio/visualisations/maps/" },
            "annotator": { text: "Made with Flourish • Create an annotator", url: "https://app.flourish.studio/@flourish/svg-annotator" },
            "audio": { text: "Made with Flourish • Create an audio player", url: "https://flourish.studio/product/interactive-content/" },
            "bar-chart-race": { text: "Made with Flourish • Create a bar chart race", url: "https://flourish.studio/visualisations/bar-chart-race/" },
            "bubble-chart": { text: "Made with Flourish • Create a bubble chart", url: "https://flourish.studio/visualisations/bubble-charts/" },
            "calculator": { text: "Made with Flourish • Create a calculator", url: "https://flourish.studio/product/interactive-content/" },
            "calendar": { text: "Made with Flourish • Create a calendar", url: "https://flourish.studio/visualisations/calendar-maker/" },
            "cards": { text: "Made with Flourish • Create interactive content", url: "https://flourish.studio/product/interactive-content/" },
            "chart": { text: "Made with Flourish • Create a chart", url: "https://flourish.studio/visualisations/line-bar-pie-charts/" },
            "chord": { text: "Made with Flourish • Create a chord diagram", url: "https://flourish.studio/visualisations/chord-diagrams/" },
            "connections-globe": { text: "Made with Flourish • Create a connections globe", url: "https://flourish.studio/visualisations/maps/" },
            "countdown": { text: "Made with Flourish • Create a countdown", url: "https://flourish.studio/product/interactive-content/" },
            "data-explorer": { text: "Made with Flourish • Create a data explorer", url: "https://flourish.studio/visualisations/data-explorer/" },
            "draw": { text: "Made with Flourish • Create a draw the line chart", url: "https://flourish.studio/product/interactive-content/" },
            "election": { text: "Made with Flourish • Create an election results chart", url: "https://flourish.studio/resources/elections/" },
            "gantt": { text: "Made with Flourish • Create a Gantt chart", url: "https://flourish.studio/visualisations/gantt-charts/" },
            "gauge": { text: "Made with Flourish • Create a gauge chart", url: "https://flourish.studio/visualisations/gauge-charts/" },
            "globe": { text: "Made with Flourish • Create a globe", url: "https://flourish.studio/visualisations/maps/" },
            "heatmap": { text: "Made with Flourish • Create a heatmap", url: "https://flourish.studio/visualisations/heatmaps/" },
            "hierarchy": { text: "Made with Flourish • Create a hierarchy graph", url: "https://flourish.studio/visualisations/treemaps/" },
            "interactive-diagram": { text: "Made with Flourish • Create an interactive SVG", url: "https://flourish.studio/visualisations/interactive-svg/" },
            "map": { text: "Made with Flourish • Create a map", url: "https://flourish.studio/visualisations/maps/" },
            "marimekko": { text: "Made with Flourish • Create a Marimekko chart", url: "https://flourish.studio/visualisations/marimekko-charts/" },
            "model": { text: "Made with Flourish • Create a 3D viewer", url: "https://flourish.studio/visualisations/3d-viewer/" },
            "network": { text: "Made with Flourish • Create a network graph", url: "https://flourish.studio/visualisations/network-charts/" },
            "number-ticker": { text: "Made with Flourish • Create a number ticker", url: "https://flourish.studio/product/interactive-content/" },
            "parliament": { text: "Made with Flourish • Create a parliament chart", url: "https://flourish.studio/visualisations/parliament-charts/" },
            "photo-slider": { text: "Made with Flourish • Create a photo slider", url: "https://flourish.studio/product/interactive-content/" },
            "pictogram": { text: "Made with Flourish • Create a pictogram chart", url: "https://flourish.studio/visualisations/pictogram-charts/" },
            "projection-map": { text: "Made with Flourish • Create a map", url: "https://flourish.studio/visualisations/maps/" },
            "quiz": { text: "Made with Flourish • Create a quiz", url: "https://flourish.studio/product/interactive-content/" },
            "radar": { text: "Made with Flourish • Create a radar chart", url: "https://flourish.studio/visualisations/radar-charts/" },
            "ranking": { text: "Made with Flourish • Create a line chart race", url: "https://flourish.studio/visualisations/line-chart-race/" },
            "sankey": { text: "Made with Flourish • Create a Sankey diagram", url: "https://flourish.studio/visualisations/sankey-charts/" },
            "scatter": { text: "Made with Flourish • Create a scatter plot", url: "https://flourish.studio/visualisations/scatter-charts/" },
            "slope": { text: "Made with Flourish • Create a slope chart", url: "https://flourish.studio/visualisations/slope-charts/" },
            "sports": { text: "Made with Flourish • Visualize sports data", url: "https://flourish.studio/resources/sports/" },
            "story": { text: "Made with Flourish • Create a data story", url: "https://flourish.studio/product/data-storytelling/" },
            "survey": { text: "Made with Flourish • Create a survey graph", url: "https://flourish.studio/visualisations/survey-template/" },
            "table": { text: "Made with Flourish • Create a table", url: "https://flourish.studio/visualisations/create-a-table/" },
            "text-annotator": { text: "Made with Flourish • Create a text annotator", url: "https://flourish.studio/product/data-visualization/" },
            "timeline": { text: "Made with Flourish • Create a timeline", url: "https://flourish.studio/visualisations/timeline-maker/" },
            "tournament": { text: "Made with Flourish • Create a tournament chart", url: "https://flourish.studio/visualisations/tournament-chart/" },
            "webgl": { text: "Made with Flourish • Create a globe", url: "https://flourish.studio/visualisations/maps/" },
            "word-cloud": { text: "Made with Flourish • Create a word cloud", url: "https://flourish.studio/product/interactive-content/" },
        },
    },
    "es": {
        credits: {
            "default": "Creado con Flourish",
            "bar_race": { text: "Creado con Flourish", url: "https://flourish.studio/visualisations/bar-chart-race/" },
            "bar-chart-race": { text: "Creado con Flourish", url: "https://flourish.studio/visualisations/bar-chart-race/" },
        },
    },
    "fr": {
        credits: {
            "default": "Créé avec Flourish",
            "bar_race": { text: "Créé avec Flourish", url: "https://flourish.studio/visualisations/bar-chart-race/" },
            "bar-chart-race": { text: "Créé avec Flourish", url: "https://flourish.studio/visualisations/bar-chart-race/" },
        },
    },
    "it": {
        credits: {
            "default": "Creato con Flourish",
            "bar_race": { text: "Creato con Flourish", url: "https://flourish.studio/visualisations/bar-chart-race/" },
            "bar-chart-race": { text: "Creato con Flourish", url: "https://flourish.studio/visualisations/bar-chart-race/" },
        },
    },
    "mi": {
        credits: {
            "default": "Hangaia ki te Flourish",
            "bar_race": { text: "Hangaia ki te Flourish", url: "https://flourish.studio/visualisations/bar-chart-race/" },
            "bar-chart-race": { text: "Hangaia ki te Flourish", url: "https://flourish.studio/visualisations/bar-chart-race/" },
        },
    },
    "nl": {
        credits: {
            "default": "Gemaakt met Flourish",
            "bar_race": { text: "Gemaakt met Flourish", url: "https://flourish.studio/visualisations/bar-chart-race/" },
            "bar-chart-race": { text: "Gemaakt met Flourish", url: "https://flourish.studio/visualisations/bar-chart-race/" },
        },
    },
    "pt": {
        "default": "Feito com Flourish",
        "bar_race": { text: "Feito com Flourish", url: "https://flourish.studio/visualisations/bar-chart-race/" },
        "bar-chart-race": { text: "Feito com Flourish", url: "https://flourish.studio/visualisations/bar-chart-race/" },
    },
};
